// Generated by CIRCT firtool-1.62.0
module ElasticModule(	// src/test/scala/chext/Test.scala:11:7
  input         clock,	// <stdin>:10:11
                reset,	// <stdin>:11:11
  output        source1_ready,	// src/test/scala/chext/Test.scala:12:19
  input         source1_valid,	// src/test/scala/chext/Test.scala:12:19
  input  [31:0] source1_bits,	// src/test/scala/chext/Test.scala:12:19
  output        source2_ready,	// src/test/scala/chext/Test.scala:13:19
  input         source2_valid,	// src/test/scala/chext/Test.scala:13:19
  input  [31:0] source2_bits,	// src/test/scala/chext/Test.scala:13:19
  input         sink_ready,	// src/test/scala/chext/Test.scala:14:16
  output        sink_valid,	// src/test/scala/chext/Test.scala:14:16
  output [31:0] sink_bits	// src/test/scala/chext/Test.scala:14:16
);

  wire sink_valid_0 = source1_valid & source2_valid;	// src/main/scala/chext/elastic/Join.scala:41:55
  wire mkJoin_fire = sink_ready & sink_valid_0;	// src/main/scala/chext/elastic/Join.scala:41:55, :42:29
  assign source1_ready = mkJoin_fire;	// src/main/scala/chext/elastic/Join.scala:42:29, src/test/scala/chext/Test.scala:11:7
  assign source2_ready = mkJoin_fire;	// src/main/scala/chext/elastic/Join.scala:42:29, src/test/scala/chext/Test.scala:11:7
  assign sink_valid = sink_valid_0;	// src/main/scala/chext/elastic/Join.scala:41:55, src/test/scala/chext/Test.scala:11:7
  assign sink_bits = source1_bits + source2_bits;	// src/test/scala/chext/Test.scala:11:7, :18:28
endmodule

